# This is a basic workflow to help you get started with Actions

name: Definition_Build_Log

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.  COMMENTED OUT PER ERROR MESSAGE.  TROUBLESHOOTING.
      #- uses: actions/checkout@v4
      - name: List repo files
        run: |
             echo "Branch: $GITHUB_REF"
             ls -R .

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Output Commit Message word definitions to CSV
        env:
          COMMIT_MSG: ${{ github.event.head_commit.message || github.event.pull_request.title }}
          BUILD_NUMBER: ${{ github.run_number }}
        shell: pwsh
        run: ./Lookup-Dictionary.ps1 -CommitMessage $COMMIT_MSG -BuildNumber $BUILD_NUMBER
